site_name: My Site
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.top

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Ram-Deepak
      name: Github

    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ram-deepak-280991224/
      name: LinkedIn 

    - icon: fontawesome/solid/paper-plane
      link: mailto:<ramdeepak33@gmail.com>
      name: Gmail

copyright: Copyright &copy; 2022 Ram Deepak
